"""

Django settings for config project.



Generated by 'django-admin startproject' using Django 6.0.6.



For more information on this file, see

https://docs.djangoproject.com/en/6.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/6.0/ref/settings/

"""



import os

from pathlib import Path



from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent



load_dotenv(BASE_DIR / '.env')





def env(key: str, default: str | None = None) -> str:

    return os.getenv(key, default)





def env_bool(key: str, default: bool = False) -> bool:

    value = os.getenv(key)

    if value is None:

        return default

    return value.lower() in ('true', '1', 'yes', 'on')





def env_list(key: str, default: str = '') -> list[str]:

    value = os.getenv(key, default)

    return [item.strip() for item in value.split(',') if item.strip()]





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



SECRET_KEY = env('DJANGO_SECRET_KEY', 'django-insecure-change-me')

DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = ['172.16.3.82', 'localhost', '127.0.0.1']





# Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'corsheaders',

    'controle_aluno',

    'controle_biblioteca',

    'ninja_extra',

]



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'config.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'config.wsgi.application'





# Database

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': env('MYSQL_NAME', 'db_escola'),

        'HOST': '172.16.3.82',

        'PORT': int(env('MYSQL_PORT', '3306')),

        'USER': env('MYSQL_USER', 'root'),

        'PASSWORD': env('MYSQL_PASSWORD', ''),

    },

    'biblioteca': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': env('POSTGRES_NAME', 'db_biblioteca'),

        'HOST': '172.16.3.82',

        'PORT': int(env('POSTGRES_PORT', '5432')),

        'USER': env('POSTGRES_USER', 'postgres'),

        'PASSWORD': env('POSTGRES_PASSWORD', ''),

    },

}





# Password validation

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/6.0/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/6.0/howto/static-files/



STATIC_URL = 'static/'

DATABASE_ROUTERS = ['config.routers.BancoDadosRouter']



CORS_ALLOWED_ORIGINS = env_list(

    'CORS_ALLOWED_ORIGINS',

    'http://localhost:5173,http://127.0.0.1:5173',

)


