# Generated by Django 6.0.6 on 2026-06-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autor', models.CharField(blank=True, max_length=225, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controle_biblioteca.tbcategoria')),
            ],
            options={
                'db_table': 'tb_livros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEmprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_biblioteca.tblivros')),
            ],
            options={
                'db_table': 'tb_emprestimos',
                'managed': True,
            },
        ),
    ]
